### Sign-up
POST http://localhost:8000/auth/sportsman/sign-up
Content-Type: application/json

{
  "name": "German",
  "surname": "Bogatov",
  "phone": "89527205825",
  "email": "bogatovgrmn@gmail.com",
  "password": "23Bogatov"
}



### Sign-in
POST http://localhost:8000/auth/sportsman/sign-in
Content-Type: application/json

{
  "email": "bogatovgrmn@gmail.com",
  "password": "23Bogatov"
}


### Refresh
POST http://localhost:8000/auth/sportsman/refresh=dd7e03e1-8000-40c6-a722-e1bd064e2b65
Content-Type: application/json


### get sportsman
GET http://localhost:8000/sportsman
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJzcG9ydHNtYW4iLCJleHAiOjE2NjY5MDQ1MDYsImp0aSI6Ijk4Njg4ZjFjLTlmZTEtNGJhMy1iMDgwLWVkYmE2ZDczZjFmYyIsImVtYWlsIjoiYm9nYXRvdmdybW5AZ21haWwuY29tIn0.gM9A9a96bKiJIiNQmlzFF2wMqlVm8uAq6PMkj2VoRV0

{
}

### Sign-up scout
POST http://localhost:8000/auth/scout/sign-up
Content-Type: application/json

{
  "name": "German",
  "surname": "Bogatov",
  "phone": "89527205825",
  "email": "bogatovgrmn@gmail.com",
  "password": "23Bogatov"
}

### Sign-in Scout
POST http://localhost:8000/auth/scout/sign-in
Content-Type: application/json

{
  "email": "bogatovgrmn@gmail.com",
  "password": "23Bogatov"
}

### get Scout
GET http://localhost:8000/scout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJzY291dCIsImV4cCI6MTY2Njk2MjA1NSwianRpIjoiM2ZjZWY1YzYtOGIwZi00MWJkLTgxZWYtOGFjYjc3MDEzZmY2IiwiZW1haWwiOiJib2dhdG92Z3JtbkBnbWFpbC5jb20ifQ.tysVb3AmcuUVf2gAJzWqefzCs-0GZY9mvJJ71zaGNOo

{
}